"""Application-wide constants."""

from __future__ import annotations

from config.constants.betterstack import (
    BETTERSTACK_PASSWORD_ENV,
    BETTERSTACK_QUERY_ENDPOINT_ENV,
    BETTERSTACK_SOURCES_ENV,
    BETTERSTACK_USERNAME_ENV,
)
from config.constants.billing import (
    CREDITS_HTTP_TIMEOUT_SECONDS,
    MACHINE_SECRET_ENV,
    ORGANIZATION_ID_ENV,
    USAGE_SECRET_ENV,
    WEBAPP_URL_ENV,
)
from config.constants.coralogix import (
    CORALOGIX_API_KEY_ENV,
    CORALOGIX_APPLICATION_NAME_ENV,
    CORALOGIX_BASE_URL_ENV,
    CORALOGIX_SUBSYSTEM_NAME_ENV,
)
from config.constants.dagster import DAGSTER_API_TOKEN_ENV, DAGSTER_ENDPOINT_ENV
from config.constants.datadog import (
    DATADOG_API_KEY_ENV,
    DATADOG_APP_KEY_ENV,
    DATADOG_SITE_ENV,
)
from config.constants.gitlab import GITLAB_AUTH_TOKEN_ENV, GITLAB_BASE_URL_ENV
from config.constants.groundcover import (
    GROUNDCOVER_API_KEY_ENV,
    GROUNDCOVER_BACKEND_ID_ENV,
    GROUNDCOVER_MCP_TOKEN_ENV,
    GROUNDCOVER_MCP_URL_ENV,
    GROUNDCOVER_TENANT_UUID_ENV,
    GROUNDCOVER_TIMEZONE_ENV,
)
from config.constants.helm import (
    HELM_KUBE_CONTEXT_ENV,
    HELM_KUBECONFIG_ENV,
    HELM_NAMESPACE_ENV,
    HELM_PATH_ENV,
)
from config.constants.honeycomb import (
    HONEYCOMB_API_KEY_ENV,
    HONEYCOMB_BASE_URL_ENV,
    HONEYCOMB_DATASET_ENV,
)
from config.constants.incident_io import INCIDENT_IO_API_KEY_ENV, INCIDENT_IO_BASE_URL_ENV
from config.constants.investigation import MAX_INVESTIGATION_LOOPS
from config.constants.jenkins import (
    JENKINS_API_TOKEN_ENV,
    JENKINS_BASE_URL_ENV,
    JENKINS_USERNAME_ENV,
)
from config.constants.llm import (
    AZURE_OPENAI_API_KEY_ENV,
    AZURE_OPENAI_API_VERSION_ENV,
    AZURE_OPENAI_BASE_URL_ENV,
)
from config.constants.mariadb import (
    MARIADB_DATABASE_ENV,
    MARIADB_HOST_ENV,
    MARIADB_PASSWORD_ENV,
    MARIADB_PORT_ENV,
    MARIADB_SSL_ENV,
    MARIADB_USERNAME_ENV,
)
from config.constants.mongodb import (
    MONGODB_AUTH_SOURCE_ENV,
    MONGODB_CONNECTION_STRING_ENV,
    MONGODB_DATABASE_ENV,
    MONGODB_TLS_ENV,
)
from config.constants.mongodb_atlas import (
    MONGODB_ATLAS_BASE_URL_ENV,
    MONGODB_ATLAS_PRIVATE_KEY_ENV,
    MONGODB_ATLAS_PROJECT_ID_ENV,
    MONGODB_ATLAS_PUBLIC_KEY_ENV,
)
from config.constants.mysql import (
    MYSQL_DATABASE_ENV,
    MYSQL_HOST_ENV,
    MYSQL_PASSWORD_ENV,
    MYSQL_PORT_ENV,
    MYSQL_SSL_MODE_ENV,
    MYSQL_USERNAME_ENV,
)
from config.constants.openclaw import (
    OPENCLAW_MCP_ARGS_ENV,
    OPENCLAW_MCP_AUTH_TOKEN_ENV,
    OPENCLAW_MCP_COMMAND_ENV,
    OPENCLAW_MCP_MODE_ENV,
    OPENCLAW_MCP_URL_ENV,
)
from config.constants.pagerduty import PAGERDUTY_API_KEY_ENV, PAGERDUTY_BASE_URL_ENV
from config.constants.paths import (
    INTEGRATIONS_STORE_PATH,
    OPENSRE_HOME_DIR,
    OPENSRE_TMP_DIR,
    ensure_opensre_tmp_dir,
    get_store_path,
)
from config.constants.platform import IS_WINDOWS
from config.constants.postgresql import (
    POSTGRESQL_DATABASE_ENV,
    POSTGRESQL_HOST_ENV,
    POSTGRESQL_PASSWORD_ENV,
    POSTGRESQL_PORT_ENV,
    POSTGRESQL_SSL_MODE_ENV,
    POSTGRESQL_USERNAME_ENV,
)
from config.constants.posthog import (
    DEFAULT_POSTHOG_TIMEOUT_SECONDS,
    DEFAULT_POSTHOG_URL,
    POSTHOG_BASE_URL_ENV,
    POSTHOG_CAPTURE_API_KEY,
    POSTHOG_HOST,
    POSTHOG_PERSONAL_API_KEY_ENV,
    POSTHOG_PROJECT_ID_ENV,
    POSTHOG_TIMEOUT_SECONDS_ENV,
)
from config.constants.posthog_mcp import (
    POSTHOG_MCP_AUTH_TOKEN_ENV,
    POSTHOG_MCP_PROJECT_ID_ENV,
    POSTHOG_MCP_URL_ENV,
)
from config.constants.redis import (
    REDIS_DATABASE_ENV,
    REDIS_HOST_ENV,
    REDIS_PASSWORD_ENV,
    REDIS_PORT_ENV,
    REDIS_SSL_ENV,
    REDIS_USERNAME_ENV,
)
from config.constants.sentry import (
    DEFAULT_SENTRY_BASE_URL,
    SENTRY_AUTH_TOKEN_ENV,
    SENTRY_BASE_URL_ENV,
    SENTRY_DSN,
    SENTRY_ERROR_SAMPLE_RATE,
    SENTRY_IN_APP_INCLUDE,
    SENTRY_MAX_BREADCRUMBS,
    SENTRY_ORGANIZATION_SLUG_ENV,
    SENTRY_PROJECT_SLUG_ENV,
    SENTRY_TRACES_SAMPLE_RATE,
)
from config.constants.sentry_mcp import (
    SENTRY_MCP_AUTH_TOKEN_ENV,
    SENTRY_MCP_HOST_ENV,
    SENTRY_MCP_URL_ENV,
)
from config.constants.servicenow import (
    SERVICENOW_INSTANCE_URL_ENV,
    SERVICENOW_PASSWORD_ENV,
    SERVICENOW_USERNAME_ENV,
)
from config.constants.signoz import SIGNOZ_API_KEY_ENV, SIGNOZ_URL_ENV
from config.constants.smtp import (
    SMTP_DEFAULT_TO_ENV,
    SMTP_FROM_ADDRESS_ENV,
    SMTP_HOST_ENV,
    SMTP_PASSWORD_ENV,
    SMTP_PORT_ENV,
    SMTP_SECURITY_ENV,
    SMTP_USERNAME_ENV,
)
from config.constants.telegram import (
    TELEGRAM_BOT_TOKEN_ENV,
    TELEGRAM_DEFAULT_CHAT_ID_ENV,
)
from config.constants.tempo import (
    TEMPO_API_KEY_ENV,
    TEMPO_ORG_ID_ENV,
    TEMPO_PASSWORD_ENV,
    TEMPO_URL_ENV,
    TEMPO_USERNAME_ENV,
)
from config.constants.temporal import (
    TEMPORAL_API_KEY_ENV,
    TEMPORAL_BASE_URL_ENV,
    TEMPORAL_NAMESPACE_ENV,
)
from config.constants.tracer import TRACER_BASE_URL_ENV, TRACER_JWT_TOKEN_ENV
from config.constants.twilio import (
    TWILIO_ACCOUNT_SID_ENV,
    TWILIO_AUTH_TOKEN_ENV,
    TWILIO_WHATSAPP_FROM_ENV,
    WHATSAPP_DEFAULT_TO_ENV,
)
from config.constants.vercel import VERCEL_API_TOKEN_ENV, VERCEL_TEAM_ID_ENV
from config.constants.x_mcp import X_MCP_AUTH_TOKEN_ENV, X_MCP_URL_ENV

__all__ = [
    "AZURE_OPENAI_API_KEY_ENV",
    "AZURE_OPENAI_API_VERSION_ENV",
    "AZURE_OPENAI_BASE_URL_ENV",
    "BETTERSTACK_PASSWORD_ENV",
    "BETTERSTACK_QUERY_ENDPOINT_ENV",
    "BETTERSTACK_SOURCES_ENV",
    "BETTERSTACK_USERNAME_ENV",
    "CORALOGIX_API_KEY_ENV",
    "CORALOGIX_APPLICATION_NAME_ENV",
    "CORALOGIX_BASE_URL_ENV",
    "CORALOGIX_SUBSYSTEM_NAME_ENV",
    "CREDITS_HTTP_TIMEOUT_SECONDS",
    "DAGSTER_API_TOKEN_ENV",
    "DAGSTER_ENDPOINT_ENV",
    "DATADOG_API_KEY_ENV",
    "DATADOG_APP_KEY_ENV",
    "DATADOG_SITE_ENV",
    "DEFAULT_POSTHOG_TIMEOUT_SECONDS",
    "DEFAULT_POSTHOG_URL",
    "DEFAULT_SENTRY_BASE_URL",
    "GITLAB_AUTH_TOKEN_ENV",
    "GITLAB_BASE_URL_ENV",
    "GROUNDCOVER_API_KEY_ENV",
    "GROUNDCOVER_BACKEND_ID_ENV",
    "GROUNDCOVER_MCP_TOKEN_ENV",
    "GROUNDCOVER_MCP_URL_ENV",
    "GROUNDCOVER_TENANT_UUID_ENV",
    "GROUNDCOVER_TIMEZONE_ENV",
    "HELM_KUBECONFIG_ENV",
    "HELM_KUBE_CONTEXT_ENV",
    "HELM_NAMESPACE_ENV",
    "HELM_PATH_ENV",
    "HONEYCOMB_API_KEY_ENV",
    "HONEYCOMB_BASE_URL_ENV",
    "HONEYCOMB_DATASET_ENV",
    "INCIDENT_IO_API_KEY_ENV",
    "INCIDENT_IO_BASE_URL_ENV",
    "INTEGRATIONS_STORE_PATH",
    "IS_WINDOWS",
    "JENKINS_API_TOKEN_ENV",
    "JENKINS_BASE_URL_ENV",
    "JENKINS_USERNAME_ENV",
    "MACHINE_SECRET_ENV",
    "MAX_INVESTIGATION_LOOPS",
    "MARIADB_DATABASE_ENV",
    "MARIADB_HOST_ENV",
    "MARIADB_PASSWORD_ENV",
    "MARIADB_PORT_ENV",
    "MARIADB_SSL_ENV",
    "MARIADB_USERNAME_ENV",
    "MONGODB_AUTH_SOURCE_ENV",
    "MONGODB_CONNECTION_STRING_ENV",
    "MONGODB_DATABASE_ENV",
    "MONGODB_TLS_ENV",
    "MONGODB_ATLAS_BASE_URL_ENV",
    "MONGODB_ATLAS_PRIVATE_KEY_ENV",
    "MONGODB_ATLAS_PROJECT_ID_ENV",
    "MONGODB_ATLAS_PUBLIC_KEY_ENV",
    "MYSQL_DATABASE_ENV",
    "MYSQL_HOST_ENV",
    "MYSQL_PASSWORD_ENV",
    "MYSQL_PORT_ENV",
    "MYSQL_SSL_MODE_ENV",
    "MYSQL_USERNAME_ENV",
    "OPENCLAW_MCP_ARGS_ENV",
    "OPENCLAW_MCP_AUTH_TOKEN_ENV",
    "OPENCLAW_MCP_COMMAND_ENV",
    "OPENCLAW_MCP_MODE_ENV",
    "OPENCLAW_MCP_URL_ENV",
    "OPENSRE_HOME_DIR",
    "OPENSRE_TMP_DIR",
    "ORGANIZATION_ID_ENV",
    "PAGERDUTY_API_KEY_ENV",
    "PAGERDUTY_BASE_URL_ENV",
    "POSTGRESQL_DATABASE_ENV",
    "POSTGRESQL_HOST_ENV",
    "POSTGRESQL_PASSWORD_ENV",
    "POSTGRESQL_PORT_ENV",
    "POSTGRESQL_SSL_MODE_ENV",
    "POSTGRESQL_USERNAME_ENV",
    "POSTHOG_BASE_URL_ENV",
    "POSTHOG_CAPTURE_API_KEY",
    "POSTHOG_HOST",
    "POSTHOG_MCP_AUTH_TOKEN_ENV",
    "POSTHOG_MCP_PROJECT_ID_ENV",
    "POSTHOG_MCP_URL_ENV",
    "POSTHOG_PERSONAL_API_KEY_ENV",
    "POSTHOG_PROJECT_ID_ENV",
    "POSTHOG_TIMEOUT_SECONDS_ENV",
    "REDIS_DATABASE_ENV",
    "REDIS_HOST_ENV",
    "REDIS_PASSWORD_ENV",
    "REDIS_PORT_ENV",
    "REDIS_SSL_ENV",
    "REDIS_USERNAME_ENV",
    "SENTRY_AUTH_TOKEN_ENV",
    "SENTRY_BASE_URL_ENV",
    "SENTRY_DSN",
    "SENTRY_ERROR_SAMPLE_RATE",
    "SENTRY_IN_APP_INCLUDE",
    "SENTRY_MAX_BREADCRUMBS",
    "SENTRY_MCP_AUTH_TOKEN_ENV",
    "SENTRY_MCP_HOST_ENV",
    "SENTRY_MCP_URL_ENV",
    "SENTRY_ORGANIZATION_SLUG_ENV",
    "SENTRY_PROJECT_SLUG_ENV",
    "SENTRY_TRACES_SAMPLE_RATE",
    "SERVICENOW_INSTANCE_URL_ENV",
    "SERVICENOW_PASSWORD_ENV",
    "SERVICENOW_USERNAME_ENV",
    "SIGNOZ_API_KEY_ENV",
    "SIGNOZ_URL_ENV",
    "SMTP_DEFAULT_TO_ENV",
    "SMTP_FROM_ADDRESS_ENV",
    "SMTP_HOST_ENV",
    "SMTP_PASSWORD_ENV",
    "SMTP_PORT_ENV",
    "SMTP_SECURITY_ENV",
    "SMTP_USERNAME_ENV",
    "TELEGRAM_BOT_TOKEN_ENV",
    "TELEGRAM_DEFAULT_CHAT_ID_ENV",
    "TEMPO_API_KEY_ENV",
    "TEMPO_ORG_ID_ENV",
    "TEMPO_PASSWORD_ENV",
    "TEMPO_URL_ENV",
    "TEMPO_USERNAME_ENV",
    "TEMPORAL_API_KEY_ENV",
    "TEMPORAL_BASE_URL_ENV",
    "TEMPORAL_NAMESPACE_ENV",
    "TRACER_BASE_URL_ENV",
    "TRACER_JWT_TOKEN_ENV",
    "TWILIO_ACCOUNT_SID_ENV",
    "TWILIO_AUTH_TOKEN_ENV",
    "TWILIO_WHATSAPP_FROM_ENV",
    "USAGE_SECRET_ENV",
    "VERCEL_API_TOKEN_ENV",
    "VERCEL_TEAM_ID_ENV",
    "WEBAPP_URL_ENV",
    "WHATSAPP_DEFAULT_TO_ENV",
    "X_MCP_AUTH_TOKEN_ENV",
    "X_MCP_URL_ENV",
    "ensure_opensre_tmp_dir",
    "get_store_path",
]
