"""Azure SQL environment variable names."""

from __future__ import annotations

AZURE_SQL_SERVER_ENV = "AZURE_SQL_SERVER"
AZURE_SQL_DATABASE_ENV = "AZURE_SQL_DATABASE"
AZURE_SQL_PORT_ENV = "AZURE_SQL_PORT"
AZURE_SQL_USERNAME_ENV = "AZURE_SQL_USERNAME"
AZURE_SQL_PASSWORD_ENV = "AZURE_SQL_PASSWORD"
AZURE_SQL_DRIVER_ENV = "AZURE_SQL_DRIVER"
AZURE_SQL_ENCRYPT_ENV = "AZURE_SQL_ENCRYPT"

__all__ = [
    "AZURE_SQL_DATABASE_ENV",
    "AZURE_SQL_DRIVER_ENV",
    "AZURE_SQL_ENCRYPT_ENV",
    "AZURE_SQL_PASSWORD_ENV",
    "AZURE_SQL_PORT_ENV",
    "AZURE_SQL_SERVER_ENV",
    "AZURE_SQL_USERNAME_ENV",
]
