"""Grafana environment variable names."""

from __future__ import annotations

GRAFANA_INSTANCE_URL_ENV = "GRAFANA_INSTANCE_URL"
GRAFANA_READ_TOKEN_ENV = "GRAFANA_READ_TOKEN"
GRAFANA_VERIFY_SSL_ENV = "GRAFANA_VERIFY_SSL"
GRAFANA_CA_BUNDLE_ENV = "GRAFANA_CA_BUNDLE"

__all__ = [
    "GRAFANA_CA_BUNDLE_ENV",
    "GRAFANA_INSTANCE_URL_ENV",
    "GRAFANA_READ_TOKEN_ENV",
    "GRAFANA_VERIFY_SSL_ENV",
]
